name: Build Starter Template

on:
  workflow_dispatch:
  push:
    branches:
      - darwin
    paths:
      - 'templates/starter/**'
  pull_request:
    branches:
      - darwin
    paths:
      - 'templates/starter/**'

jobs:
  build-starter-template:
    uses: ./.github/workflows/build-template.yml
    with:
      template: 'starter'
      arch: 'aarch64-darwin'
