name: Build Starter Template

on:
  workflow_dispatch:
  push:
    branches:
      - darwin
    paths:
      - 'templates/container/**'
  pull_request:
    branches:
      - darwin
    paths:
      - 'templates/container/**'

jobs:
  build-starter-template:
    uses: ./.github/workflows/build-template.yml
    with:
      template: 'container'
      arch: 'aarch64-darwin'
